// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	
	int N = Integer.parseInt(args[0]);
	
	int above =0;
	int below=0;

	for (int i=0; i<N; i++) {
	
		double randomNum = Math.random();
		if (randomNum>0.5) {
			above++;

		} else {
			below++;
		}


	}

	System.out.println(">0.5: " + above + " times");
	System.out.println("<=0.5: " + below + " times");

	if (below !=0) {

		double ratio = (double) above/below;
		System.out.println("Ratio: " + ratio);
	}

	}
}

